title: Adetunji Adegbite
description: Senior Mobile Engineer | Flutter & Android
show_downloads: false
google_analytics: # your GA ID if you want tracking
theme: jekyll-theme-cayman

# Optional links (show up as navigation buttons)
github:
  is_project_page: false
  owner_url: https://github.com/jayhymn
linkedin: https://linkedin.com/in/adetunji-adegbite
stackoverflow: https://stackoverflow.com/users/9884414/jayhymn
email: adetunji.adegbite1@gmail.com
